#!/bin/bash



if [ "$1" == "" ]; then
 echo "*** Error: You haven't specified a test."
 echo "SYNOPSIS: run-test TESTNAME"
 exit
fi

LD_LIBRARY_PATH=../../../bin:$LD_LIBRARY_PATH ceps ../../../model/common.ceps \
../../../ceps_plugin/src/mme_defs.ceps \
../../../model/timing.ceps \
../../../ceps_plugin/src/mme_handlers.ceps \
../../../ceps_plugin/src/setup_mme_plugin.ceps \
$1 \
sim.with_mme_plugin.ceps \
 --pluginlibslac4ceps.so
